import 'package:flutter/material.dart';
import 'spell_effects.dart';

class Spell {
  final String id;
  final String name; // نام انگلیسی - برای تشخیص گفتار استفاده می‌شود
  final String incant; // نام فارسی - فقط برای نمایش
  final String desc;
  final IconData icon;
  final EffectStyle effectStyle;
  final Color effectColor;
  final Color secondaryColor;
  final bool reverse;

  const Spell({
    required this.id,
    required this.name,
    required this.incant,
    required this.desc,
    required this.icon,
    required this.effectStyle,
    required this.effectColor,
    this.secondaryColor = Colors.white,
    this.reverse = false,
  });
}

const Color kGold = Color(0xFFC9A227);

const List<Spell> allSpells = [
  Spell(
    id: 'giant_dungbomb',
    name: 'Giant Dungbomb',
    incant: 'بمب گنده‌ی بو',
    desc: 'ایجاد بمب بویناک که دود و بوی بد پخش می‌کند.',
    icon: Icons.cloud,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.brown,
    secondaryColor: Colors.green,
    reverse: true,
  ),
  Spell(
    id: 'cheering_charm',
    name: 'Cheering Charm',
    incant: 'طلسم شادی',
    desc: 'ایجاد حس شادی و نشاط ناگهانی در فرد.',
    icon: Icons.sentiment_very_satisfied,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.pinkAccent,
    secondaryColor: Colors.yellow,
  ),
  Spell(
    id: 'silencio',
    name: 'Silencio',
    incant: 'سایلنسیو',
    desc: 'خاموش کردن کامل صدای هدف.',
    icon: Icons.volume_off,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.blueGrey,
  ),
  Spell(
    id: 'arresto_momentum',
    name: 'Arresto Momentum',
    incant: 'آرستو مومنتوم',
    desc: 'کاهش سرعت حرکت یا سقوط یک جسم.',
    icon: Icons.slow_motion_video,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.lightBlue,
  ),
  Spell(
    id: 'locomotor_mortis',
    name: 'Locomotor Mortis',
    incant: 'لوکوموتور مورتیس',
    desc: 'به‌هم چسباندن پاها و از کار انداختن راه رفتن.',
    icon: Icons.block,
    effectStyle: EffectStyle.wrapLines,
    effectColor: Colors.deepPurple,
  ),
  Spell(
    id: 'disillusionment_charm',
    name: 'Disillusionment Charm',
    incant: 'دیسیلوژنمنت چارم',
    desc: 'همرنگ کردن فرد با محیط اطراف برای استتار.',
    icon: Icons.visibility_off,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.grey,
  ),
  Spell(
    id: 'descendo',
    name: 'Descendo',
    incant: 'دسندو',
    desc: 'پایین آوردن یک جسم معلق.',
    icon: Icons.arrow_downward,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.brown,
  ),
  Spell(
    id: 'deletrius',
    name: 'Deletrius',
    incant: 'دیلیتریوس',
    desc: 'پاک کردن تصاویر و آثار جادویی ایجاد شده.',
    icon: Icons.clear,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.grey,
    secondaryColor: Colors.white,
  ),
  Spell(
    id: 'pack_charm',
    name: 'Pack Charm',
    incant: 'طلسم بسته‌بندی',
    desc: 'جمع‌آوری خودکار وسایل داخل چمدان.',
    icon: Icons.luggage,
    effectStyle: EffectStyle.spiral,
    effectColor: Colors.brown,
  ),
  Spell(
    id: 'muffliato',
    name: 'Muffliato',
    incant: 'مافلیاتو',
    desc: 'ایجاد وزوز در گوش اطرافیان برای جلوگیری از شنیدن مکالمه.',
    icon: Icons.hearing_disabled,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.teal,
  ),
  Spell(
    id: 'confundus',
    name: 'Confundus',
    incant: 'کونفاندوس',
    desc: 'گیج و سردرگم کردن ذهن هدف.',
    icon: Icons.blur_on,
    effectStyle: EffectStyle.spiral,
    effectColor: Colors.deepPurpleAccent,
  ),
  Spell(
    id: 'lumos_maxima',
    name: 'Lumos Maxima',
    incant: 'لوموس ماکسیما',
    desc: 'تولید نوری بسیار قوی‌تر از لوموس عادی.',
    icon: Icons.wb_sunny,
    effectStyle: EffectStyle.beam,
    effectColor: Colors.yellowAccent,
    secondaryColor: Colors.white,
  ),
  Spell(
    id: 'drought_charm',
    name: 'Drought Charm',
    incant: 'طلسم خشکسالی',
    desc: 'خشک کردن کامل یک منبع آب.',
    icon: Icons.grain,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Color(0xFFC9A876),
  ),
  Spell(
    id: 'knitting_charm',
    name: 'Knitting Charm',
    incant: 'طلسم بافندگی',
    desc: 'بافتن خودکار پارچه یا لباس.',
    icon: Icons.checkroom,
    effectStyle: EffectStyle.wrapLines,
    effectColor: Colors.pink,
  ),
  Spell(
    id: 'relashio',
    name: 'Relashio',
    incant: 'ریلاشیو',
    desc: 'رها کردن هدف از قید و بند با جرقه یا آب.',
    icon: Icons.flash_on,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.orange,
    secondaryColor: Colors.blue,
  ),
  Spell(
    id: 'bubble_head_charm',
    name: 'Bubble Head Charm',
    incant: 'طلسم حباب سر',
    desc: 'ایجاد حباب هوا دور سر برای تنفس زیر آب.',
    icon: Icons.bubble_chart,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.cyan,
    reverse: true,
  ),
  Spell(
    id: 'gouging_spell',
    name: 'Gouging Spell',
    incant: 'طلسم شیاردهی',
    desc: 'ایجاد شیارهای عمیق روی سطح هدف.',
    icon: Icons.terrain,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.redAccent,
  ),
  Spell(
    id: 'flipendo_maxima',
    name: 'Flipendo Maxima',
    incant: 'فلیپندو ماکسیما',
    desc: 'نسخه‌ی قدرتمندتر فلیپندو برای پرتاب هدف به عقب.',
    icon: Icons.double_arrow,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.indigo,
  ),
  Spell(
    id: 'blackboard_writing_spell',
    name: 'Blackboard Writing Spell',
    incant: 'طلسم نویسنده‌ی تخته',
    desc: 'نوشتن خودکار متن روی تخته‌سیاه.',
    icon: Icons.edit,
    effectStyle: EffectStyle.wrapLines,
    effectColor: Colors.white,
  ),
  Spell(
    id: 'cleaning_charm',
    name: 'Cleaning Charm',
    incant: 'طلسم تمیزکاری',
    desc: 'تمیز کردن سریع سطوح کثیف.',
    icon: Icons.cleaning_services,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.lightBlueAccent,
  ),
  Spell(
    id: 'blue_sparks',
    name: 'Blue Sparks',
    incant: 'جرقه‌های آبی',
    desc: 'پرتاب جرقه‌های آبی رنگ هشداردهنده.',
    icon: Icons.auto_awesome,
    effectStyle: EffectStyle.burstUp,
    effectColor: Colors.blue,
  ),
  Spell(
    id: 'aguamenti',
    name: 'Aguamenti',
    incant: 'آگوامنتی',
    desc: 'تولید جریان آب از نوک چوبدستی.',
    icon: Icons.water_drop,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.blue,
  ),
  Spell(
    id: 'extinguishing_charm',
    name: 'Extinguishing Charm',
    incant: 'طلسم خاموش‌کننده',
    desc: 'خاموش کردن سریع آتش.',
    icon: Icons.water,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.blueGrey,
  ),
  Spell(
    id: 'ascendio',
    name: 'Ascendio',
    incant: 'آسندیو',
    desc: 'پرتاب جادوگر به سمت بالا و بیرون از آب.',
    icon: Icons.upgrade,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.cyan,
    reverse: true,
  ),
  Spell(
    id: 'anti_alohomora_charm',
    name: 'Anti-Alohomora Charm',
    incant: 'طلسم ضد آلوهومورا',
    desc: 'ایجاد حفاظ در برابر طلسم بازکننده‌ی قفل.',
    icon: Icons.lock,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.indigo,
  ),
  Spell(
    id: 'lumos_solem',
    name: 'Lumos Solem',
    incant: 'لوموس سولم',
    desc: 'ایجاد نور شدید همانند نور خورشید.',
    icon: Icons.brightness_high,
    effectStyle: EffectStyle.beam,
    effectColor: Colors.amber,
  ),
  Spell(
    id: 'impervius',
    name: 'Impervius',
    incant: 'امپرویو',
    desc: 'ضدآب کردن سطح یک جسم.',
    icon: Icons.umbrella,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.lightBlue,
  ),
  Spell(
    id: 'lumos',
    name: 'Lumos',
    incant: 'لوموس',
    desc: 'روشن کردن نوک چوبدستی به عنوان چراغ‌قوه.',
    icon: Icons.lightbulb,
    effectStyle: EffectStyle.beam,
    effectColor: kGold,
  ),
  Spell(
    id: 'expelliarmus',
    name: 'Expelliarmus',
    incant: 'اکسپلیارموس',
    desc: 'خلع سلاح کردن حریف.',
    icon: Icons.flash_on,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.red,
  ),
  Spell(
    id: 'ritusempra',
    name: 'Ritusempra',
    incant: 'ریتوسمپرا',
    desc: 'ایجاد سکسکه‌های شدید و مزاحم در هدف.',
    icon: Icons.sentiment_dissatisfied,
    effectStyle: EffectStyle.burstUp,
    effectColor: Colors.pink,
  ),
  Spell(
    id: 'wingardium_leviosa',
    name: 'Wingardium Leviosa',
    incant: 'وینگاردیم لویوسا',
    desc: 'شناور کردن و بلند کردن اجسام در هوا.',
    icon: Icons.air,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.lightBlue,
    reverse: true,
  ),
  Spell(
    id: 'alohomora',
    name: 'Alohomora',
    incant: 'آلوهومورا',
    desc: 'باز کردن قفل‌های ساده.',
    icon: Icons.lock_open,
    effectStyle: EffectStyle.rings,
    effectColor: kGold,
  ),
  Spell(
    id: 'flipendo',
    name: 'Flipendo',
    incant: 'فلیپندو',
    desc: 'هل دادن و پرتاب هدف به عقب.',
    icon: Icons.keyboard_arrow_left,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.blue,
  ),
  Spell(
    id: 'nox',
    name: 'Nox',
    incant: 'ناکس',
    desc: 'خاموش کردن نور نوک چوبدستی.',
    icon: Icons.nights_stay,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.black,
  ),
  Spell(
    id: 'reluctant_reversers_charm',
    name: 'Charm to cure Reluctant Reversers',
    incant: 'طلسم درمان بازگشت‌ناپذیری',
    desc: 'طلسمی برای درمان و برطرف کردن اثرات یک شوخی جادویی.',
    icon: Icons.healing,
    effectStyle: EffectStyle.burstUp,
    effectColor: Colors.green,
  ),
  Spell(
    id: 'expulso',
    name: 'Expulso',
    incant: 'اکسپولسو',
    desc: 'ایجاد انفجار قدرتمند در هدف.',
    icon: Icons.whatshot,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.deepOrange,
  ),
  Spell(
    id: 'engorgio',
    name: 'Engorgio',
    incant: 'انگورجیو',
    desc: 'بزرگ کردن اندازه‌ی یک جسم.',
    icon: Icons.zoom_in,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.green,
  ),
  Spell(
    id: 'incendio',
    name: 'Incendio',
    incant: 'اینسندیو',
    desc: 'تولید و پرتاب آتش جادویی.',
    icon: Icons.local_fire_department,
    effectStyle: EffectStyle.burstUp,
    effectColor: Colors.deepOrange,
    secondaryColor: Colors.red,
  ),
  Spell(
    id: 'episkey',
    name: 'Episkey',
    incant: 'اپیسکی',
    desc: 'درمان سریع آسیب‌های جزئی بدن.',
    icon: Icons.medical_services,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.lightGreen,
  ),
  Spell(
    id: 'reducio',
    name: 'Reducio',
    incant: 'ریدیوسیو',
    desc: 'کوچک کردن اندازه‌ی یک جسم.',
    icon: Icons.zoom_out,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.purple,
  ),
  Spell(
    id: 'meteolojinx_recanto',
    name: 'Meteolojinx Recanto',
    incant: 'متئولوجینکس ریکانتو',
    desc: 'خنثی کردن طلسم‌های مربوط به آب‌وهوا.',
    icon: Icons.cloud_off,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.blueGrey,
  ),
  Spell(
    id: 'fintie_incantatem',
    name: 'Fintie Incantatem',
    incant: 'فینیته اینکانتاتم',
    desc: 'پایان دادن به اثر تمام طلسم‌های فعال روی هدف.',
    icon: Icons.stop,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.white,
  ),
  Spell(
    id: 'petrificus_totalus',
    name: 'Petrificus Totalus',
    incant: 'پتریفیکوس توتالوس',
    desc: 'بی‌حرکت و سفت کردن کامل بدن هدف مانند سنگ.',
    icon: Icons.accessibility_new,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.blueGrey,
  ),
  Spell(
    id: 'depulso',
    name: 'Depulso',
    incant: 'دیپولسو',
    desc: 'دور کردن و هل دادن یک جسم از خود.',
    icon: Icons.arrow_forward,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.blue,
  ),
  Spell(
    id: 'riddikulus',
    name: 'Riddikulus',
    incant: 'ریدیکولوس',
    desc: 'خنده‌دار کردن یک موجود ترسناک.',
    icon: Icons.theater_comedy,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.pinkAccent,
    secondaryColor: Colors.yellow,
  ),
  Spell(
    id: 'immobulus',
    name: 'Immobulus',
    incant: 'ایموبولوس',
    desc: 'متوقف کردن حرکت یک موجود یا جسم.',
    icon: Icons.pause_circle,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.cyan,
  ),
  Spell(
    id: 'glacius',
    name: 'Glaciuc',
    incant: 'گلاسیوس',
    desc: 'یخ زدن سریع سطح یک جسم.',
    icon: Icons.ac_unit,
    effectStyle: EffectStyle.overlayFade,
    effectColor: Colors.lightBlueAccent,
  ),
  Spell(
    id: 'avenseguim',
    name: 'Avenseguim',
    incant: 'اونسگویم',
    desc: 'طلسمی برای دنبال کردن و ردیابی مسیر هدف.',
    icon: Icons.explore,
    effectStyle: EffectStyle.spiral,
    effectColor: Colors.green,
  ),
  Spell(
    id: 'appare_vestigium',
    name: 'Appare Vestigium',
    incant: 'آپاره وستیجیوم',
    desc: 'آشکار کردن ردپا و آثار عبور یک موجود.',
    icon: Icons.directions_walk,
    effectStyle: EffectStyle.fallDown,
    effectColor: Colors.brown,
  ),
  Spell(
    id: 'protego',
    name: 'Protego',
    incant: 'پروتگو',
    desc: 'ایجاد سپر جادویی محافظ.',
    icon: Icons.shield,
    effectStyle: EffectStyle.rings,
    effectColor: Colors.blue,
  ),
  Spell(
    id: 'bombarda',
    name: 'Bombarda',
    incant: 'بومباردا',
    desc: 'منفجر کردن یک مانع یا در.',
    icon: Icons.whatshot,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.orange,
  ),
  Spell(
    id: 'confringo',
    name: 'Confringo',
    incant: 'کانفرینگو',
    desc: 'منفجر کردن هدف با آتش شدید.',
    icon: Icons.local_fire_department,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.deepOrange,
    secondaryColor: Colors.red,
  ),
  Spell(
    id: 'ferula',
    name: 'Ferula',
    incant: 'فرولا',
    desc: 'بستن آتل و باندپیچی روی عضو آسیب‌دیده.',
    icon: Icons.healing,
    effectStyle: EffectStyle.wrapLines,
    effectColor: Colors.white,
  ),
  Spell(
    id: 'vermillious',
    name: 'Vermillious',
    incant: 'ورمیلیوس',
    desc: 'پرتاب جرقه‌های قرمز رنگ به عنوان علامت هشدار.',
    icon: Icons.auto_awesome,
    effectStyle: EffectStyle.burstUp,
    effectColor: Colors.red,
  ),
  Spell(
    id: 'cistem_aperio',
    name: 'Cistem Aperio',
    incant: 'سیستم آپریو',
    desc: 'باز کردن قفل صندوق یا چمدان.',
    icon: Icons.inventory_2,
    effectStyle: EffectStyle.rings,
    effectColor: kGold,
  ),
  Spell(
    id: 'scourgify',
    name: 'Scourgify',
    incant: 'اسکورجیفای',
    desc: 'تمیز کردن و پاکسازی کامل یک سطح.',
    icon: Icons.cleaning_services,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.lightBlue,
  ),
  Spell(
    id: 'diffindo',
    name: 'Diffindo',
    incant: 'دیفیندو',
    desc: 'بریدن دقیق یک جسم یا پارچه.',
    icon: Icons.cut,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.grey,
  ),
  Spell(
    id: 'arania_exumai',
    name: 'Arania Exumai',
    incant: 'آرانیا اگزومای',
    desc: 'دور کردن عنکبوت‌ها و موجودات مشابه.',
    icon: Icons.bug_report,
    effectStyle: EffectStyle.burstRadial,
    effectColor: Colors.orange,
  ),
  Spell(
    id: 'colloportus',
    name: 'Colloportus',
    incant: 'کولوپورتوس',
    desc: 'قفل کردن یک در به صورت جادویی.',
    icon: Icons.lock,
    effectStyle: EffectStyle.rings,
    effectColor: Color(0xFF6B4226),
  ),
];
